extends:
  - remcohaszing
  - remcohaszing/typechecking
rules:
  no-restricted-globals: off

  '@typescript-eslint/no-misused-promises': off
  '@typescript-eslint/no-shadow': off
  '@typescript-eslint/no-unnecessary-condition': off

  import/extensions: off
  import/no-extraneous-dependencies: off
  import/no-unresolved: off

  jsdoc/require-jsdoc: off

  node/no-extraneous-import: off
  node/no-unsupported-features/es-syntax: off
  node/no-unsupported-features/node-builtins: off
